"""Frozen contracts v2 (SPEC.md §3) and the service interfaces coded against them.

Import models from here: `from backend.contracts import Project, SourceIndex, ...`.
"""

from backend.contracts.interfaces import (
    AnalysisService,
    IngestService,
    MediaService,
    OutputQA,
    ProjectStore,
    Renderer,
    SpeedProposer,
    TrimProposer,
)
from backend.contracts.models import (
    CONTRACT_MODELS,
    Analysis,
    AudioMix,
    AudioSettings,
    Clip,
    Confidence,
    Disposition,
    Export,
    Music,
    Orientation,
    Origin,
    OriginValue,
    OutputResolution,
    Project,
    Proposals,
    QAReport,
    ReasonRecord,
    RenderRecord,
    Segment,
    SegmentsProposal,
    Signals,
    SourceIndex,
    SpeedProposal,
    SpeedRange,
)

__all__ = [
    "CONTRACT_MODELS",
    "Analysis",
    "AudioMix",
    "AudioSettings",
    "Clip",
    "Confidence",
    "Disposition",
    "Export",
    "Music",
    "Orientation",
    "Origin",
    "OriginValue",
    "OutputResolution",
    "Project",
    "Proposals",
    "QAReport",
    "ReasonRecord",
    "RenderRecord",
    "Segment",
    "SegmentsProposal",
    "Signals",
    "SourceIndex",
    "SpeedProposal",
    "SpeedRange",
    # interfaces
    "AnalysisService",
    "IngestService",
    "MediaService",
    "OutputQA",
    "ProjectStore",
    "Renderer",
    "SpeedProposer",
    "TrimProposer",
]
